### ISSUE TITLE
Wrong scope in ajax.get's onSuccess

### ISSUE THREAD

**Issue by titanjer** [pedronauck/react-video#17]
The example page shows "Uncaught TypeError: undefined is not a function" at react-video.js:158 and react-video.js:172.

**Comment by atwoodjw** [comment]
I'm seeing this too.

**Comment by titanjer** [comment]
Coool! @atwoodjw 
Your commit also resolves the "Video is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory"

btw,
There is still a warning for using wrong prop!
"Warning: Unknown DOM property frameborder. Did you mean frameBorder?"

Please fix this typo and ask for a pull request!
Thank you!

**Comment by atwoodjw** [comment]
Done

**Comment by pedronauck** [comment]
Closed on new [release v1.5.3](https://github.com/pedronauck/react-video/releases/tag/v1.5.3)
