### ISSUE TITLE
Add a new maintainer or transfer ownership

### ISSUE THREAD

**Issue by jgable** [pedronauck/react-video#19]
Can you please add a new maintainer to maintain this project or officially transfer it to someone else?

The current published version is unusable without the fixes in #18 and those commits have actually been lost since their repo is gone.

I'd be happy to help you work through issues and updates if you'd like.

**Comment by pedronauck** [comment]
Sorry @jgable, I was very busy in the last weeks and can't did anything about my personal projects because that. I'm very glad that you can help me with this project, I'll put you as a maintainer, thanks a lot :+1:

**Comment by jgable** [comment]
No worries, this is a good idea for a component.  Glad I can help.

:beers:
